### ISSUE TITLE
how do i get the log?

### ISSUE THREAD

**Issue by BrishFrog** [KSP-ModularManagement/ModuleManager#27]
![image](https://github.com/KSP-ModularManagement/ModuleManager/assets/111784141/3471639d-df7e-4f78-8901-95161f2b71f1)

**Comment by Lisias** [comment]
Hi, @BrishFrog !

You will find the `KSP.log` in the same place (hopefully) you will find the `KSP_x64.exe` (or `KSP.app` in MacOS, `KSP_x64` in Linux). Unless you are using that half baked solution to bypass the PD-Launcher by editing the Steam Launcher to pinpoint directly into the executable (what, granted, used to work in the past). If you did that, you will find the `KSP.log` inside the `PDLauncher` directory.

You will find more detailed instructions on Forum on this [thread](https://forum.kerbalspaceprogram.com/topic/83212-how-to-get-support-read-first/).

**Comment by Lisias** [comment]
Closing, assuming the underlining issue was solving somehow.
